apiVersion: apps/v1
kind: Deployment
metadata:
  name: suse-app
spec:
  selector:
    matchLabels:
      app: suse-app
  template:
    metadata:
      labels:
        app: suse-app
    spec:
      containers:
      - name: web
        image: nginx:alpine
        command: ["/bin/sh", "-c"]
        args: 
          - |
            echo '<body style="background-color:black; display:flex; justify-content:center; align-items:center; height:100vh; margin:0;">
            <h1 style="color:{{ .Values.color }}; font-size:10rem; font-family:sans-serif;">SUSE</h1>
            </body>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
